title: Fouzia Sharkar
logo: file/cropped-image.png
description: Aspiring Data Scientist
#show_downloads: true
[Download My CV](assets/Fouzia_Sharkar_CV.pdf){: .btn .btn-primary }
theme: jekyll-theme-minimal
